src/book/urls.py
from django.urls import path
from . import views
app_name = 'book'
urlpatterns = [
    path('show/<int:pk>/', views.ShowBook.as_view(), name='book-detail'),
    path('add_book_comment/<int:pk>/', views.CreateBookComments.as_view(), name='book-comment'),
    path('list_book_comment/', views.ShowComments.as_view(), name='book-comment-list'),
    path('update_book_comment/<int:pk>/', views.UpdateBookComments.as_view(), name='book-comment-update'),
    path('delete_book_comment/<int:pk>/', views.DeleteBookComments.as_view(), name='book-comment-delete'),
    path('all/', views.ShowBooks.as_view(), name='book-list'),
    path('add_book/', views.CreateBook.as_view(), name='book-add'),
    path('update_book/<int:pk>/', views.UpdateBook.as_view(), name='book-update'),
    path('add_book_csv/', views.upload_file, name='book-add-csv'), 
]

src/book_reference/urls.py
from django.urls import path
from . import views
app_name = 'book_reference'
urlpatterns = [
    path('genre-create/', views.CreateGenre.as_view(), name='genre-create'),
    path('genre-update/<int:pk>/', views.UpdateGenre.as_view(), name='genre-update'),
    path('genre-delete/<int:pk>/', views.DeleteGenre.as_view(), name='genre-delete'),
    path('genre-show/<int:pk>/', views.ShowGenre.as_view(), name='genre-detail'),
    path('genres-show/', views.ShowGenres.as_view(), name='genre-list'),
    path('author-create/', views.CreateAuthor.as_view(), name='author-create'),
    path('author-update/<int:pk>/', views.UpdateAuthor.as_view(), name='author-update'),
    path('author-delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author-delete'),
    path('author-show/<int:pk>/', views.ShowAuthor.as_view(), name='author-detail'),
    path('authors-show/', views.ShowAuthors.as_view(), name='author-list'),
    path('publisher-create/', views.CreatePublisher.as_view(), name='publisher-create'),
    path('publisher-update/<int:pk>/', views.UpdatePublisher.as_view(), name='publisher-update'),
    path('publisher-delete/<int:pk>/', views.DeletePublisher.as_view(), name='publisher-delete'),
    path('publisher-show/<int:pk>/', views.ShowPublisher.as_view(), name='publisher-detail'),
    path('publishers-show/', views.ShowPublishers.as_view(), name='publisher-list'),
    path('series-create/', views.CreateSeries.as_view(), name='series-create'),
    path('series-update/<int:pk>/', views.UpdateSeries.as_view(), name='series-update'),
    path('series-delete/<int:pk>/', views.DeleteSeries.as_view(), name='series-delete'),
    path('series-show/<int:pk>/', views.ShowSeries.as_view(), name='series-detail'),
    path('series-all-show/', views.ShowSeriesAll.as_view(), name='series-list'),
]

src/proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from catalog import views as c_views

urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('refs/', include('book_reference.urls', namespace='book_reference')),
    path('order/', include('orders.urls', namespace='orders')),
    path('',views.HomePage.as_view(), name='home-page'),
    path('catalog/',include('catalog.urls', namespace='catalog')),
    path('delivery/',views.Delivery.as_view(), name='delivery'),
    path('payment/',views.Payment.as_view(), name='payment'),
    path('contacts/',views.Contacts.as_view(), name='contacts'),
    path('search/', c_views.Search.as_view(template_name='catalog/search.html'), name='search'),
    path('book/', include('book.urls', namespace='book')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin-portal/', views.AdminPortal.as_view(),name='adm-portsl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/book_reference/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.
class BookGenre(models.Model):
    name= models.CharField(
        max_length=40,
        verbose_name='Жанр'
        )
    description=models.TextField(
        verbose_name='Описание жанра',
        blank=True,
        null=True
    )
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('book_reference:genre-detail', kwargs={'pk':self.pk})


class BookPublisher(models.Model):
    name= models.CharField(
        max_length=40,
        verbose_name='Издательство'
        )
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse_lazy('book_reference:publisher-detail', kwargs={'pk':self.pk})

class BookSeries(models.Model):
    name= models.CharField(
        max_length=40,
        verbose_name='Серия'
        )
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse_lazy('book_reference:series-detail', kwargs={'pk':self.pk})

class BookAuthor(models.Model):
    name= models.CharField(
        max_length=40,
        verbose_name='Автор'
        )

    name_lower=models.CharField(
        max_length=40,
        verbose_name='Автор',
        editable=False,
        null=True,
        blank=True
    )

    def save(self, *args, **kwargs):
        self.name_lower=self.name.lower() if self.name else None
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('book_reference:author-detail', kwargs={'pk':self.pk})

src/book_reference/forms.py
from dataclasses import fields
from django import forms
from django import forms
from django.forms import ModelForm
from . import models

class GenreForm(ModelForm):
    class Meta:
        model = models.BookGenre
        fields = [
            'name',
            'description'
            ] 

class AuthorForm(ModelForm):
    class Meta:
        model = models.BookAuthor
        fields = [
            'name',
            ]             

class PublisherForm(ModelForm):
    class Meta:
        model = models.BookPublisher
        fields = [
            'name',
            ]   

class SeriesForm(ModelForm):
    class Meta:
        model = models.BookSeries
        fields = [
            'name',
            ]              

src/book_reference/views.py
from django.urls import reverse_lazy
from django.views import generic
from . import models, forms
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from home_page.views import BaseTemplatePageMixin


class CreateGenre(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.CreateView):
    model = models.BookGenre
    form_class = forms.GenreForm
    permission_required = ("book_reference.add_book_genre")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/create_genre.html'

class UpdateGenre(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.UpdateView):
    model = models.BookGenre
    form_class = forms.GenreForm
    permission_required = ("book_reference.change_book_genre")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/update_genre.html'

class ShowGenre(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.DetailView):
    model = models.BookGenre
    permission_required = ("book_reference.view_book_genre")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/detail_genre.html'

class ShowGenres(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin, generic.ListView):
    model = models.BookGenre
    permission_required = ("book_reference.view_book_genre")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/list_genres.html'

class DeleteGenre(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.DeleteView):
    model = models.BookGenre
    permission_required = ("book_reference.delete_book_genre")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/delete_genre.html'
    success_url="/refs/genres-show"


class CreateAuthor(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.CreateView):
    model = models.BookAuthor
    permission_required = ("book_reference.add_book_author")
    login_url = reverse_lazy('login')
    form_class = forms.AuthorForm
    template_name = 'book_reference/create_author.html'

class UpdateAuthor(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.UpdateView):
    model = models.BookAuthor
    form_class = forms.AuthorForm
    permission_required = ("book_reference.change_book_author")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/update_author.html'

class ShowAuthor(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.DetailView):
    model = models.BookAuthor
    permission_required = ("book_reference.view_book_author")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/detail_author.html'

class ShowAuthors(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.ListView):
    model = models.BookAuthor
    permission_required = ("book_reference.view_book_author")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/list_authors.html'

class DeleteAuthor(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin,generic.DeleteView):
    model = models.BookAuthor
    permission_required = ("book_reference.delete_book_author")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/delete_author.html'
    success_url="/refs/authors-show"


class CreatePublisher(PermissionRequiredMixin, LoginRequiredMixin,generic.CreateView):
    model = models.BookPublisher
    form_class = forms.PublisherForm
    permission_required = ("book_reference.add_book_publisher")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/create_publisher.html'

class UpdatePublisher(PermissionRequiredMixin, LoginRequiredMixin,generic.UpdateView):
    model = models.BookPublisher
    form_class = forms.PublisherForm
    permission_required = ("book_reference.change_book_publisher")
    login_url = reverse_lazy('login')   
    template_name = 'book_reference/update_publisher.html'

class ShowPublisher(PermissionRequiredMixin, LoginRequiredMixin,generic.DetailView):
    model = models.BookPublisher
    permission_required = ("book_reference.view_book_publisher")
    login_url = reverse_lazy('login')    
    template_name = 'book_reference/detail_publisher.html'

class ShowPublishers(PermissionRequiredMixin, LoginRequiredMixin,generic.ListView):
    model = models.BookPublisher
    permission_required = ("book_reference.view_book_publisher")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/list_publishers.html'

class DeletePublisher(PermissionRequiredMixin, LoginRequiredMixin,generic.DeleteView):
    model = models.BookPublisher
    permission_required = ("book_reference.delete_book_publisher")
    login_url = reverse_lazy('login')    
    template_name = 'book_reference/delete_publisher.html'
    success_url="/refs/publishers-show"


class CreateSeries(PermissionRequiredMixin, LoginRequiredMixin,generic.CreateView):
    model = models.BookSeries
    form_class = forms.SeriesForm
    permission_required = ("book_reference.add_book_series")
    login_url = reverse_lazy('login')    
    template_name = 'book_reference/create_series.html'

class UpdateSeries(PermissionRequiredMixin, LoginRequiredMixin,generic.UpdateView):
    model = models.BookSeries
    form_class = forms.SeriesForm
    permission_required = ("book_reference.change_book_series")
    login_url = reverse_lazy('login')  
    template_name = 'book_reference/update_series.html'

class ShowSeries(PermissionRequiredMixin, LoginRequiredMixin,generic.DetailView):
    model = models.BookSeries
    permission_required = ("book_reference.view_book_series")
    login_url = reverse_lazy('login')  
    template_name = 'book_reference/detail_series.html'

class ShowSeriesAll(PermissionRequiredMixin, LoginRequiredMixin,generic.ListView):
    model = models.BookSeries
    permission_required = ("book_reference.view_book_series")
    login_url = reverse_lazy('login')
    template_name = 'book_reference/list_series_all.html'

class DeleteSeries(PermissionRequiredMixin, LoginRequiredMixin,generic.DeleteView):
    model = models.BookSeries
    permission_required = ("book_reference.view_book_series")
    login_url = reverse_lazy('login')  
    template_name = 'book_reference/delete_series.html'
    success_url="/refs/series-all-show"  

src/book_reference/templates/book_reference/create_author.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Создание автора</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/create_publisher.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание издательства
{% endblock title %}
{% block body %}
    <h1>Создание издательства</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/delete_author.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Удаление автора
{% endblock title %}
{% block body %}
    <h1>Удаление автора</h1>
    {{object.name}}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/delete_publisher.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Удаление издательства
{% endblock title %}
{% block body %}
    <h1>Удаление издательства</h1>
    {{object.name}}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/delete_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Удаление серии
{% endblock title %}
{% block body %}
    <h1>Удаление серии</h1>
    {{object.name}}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/detail_author.html
{% extends 'base.html' %}
{% block title %}
Просмотр автора
{% endblock title %}
{% block body %}
    <h1>Просмотр автора</h1>
    {{object.name}}
    <form action="" method="post">
        {% csrf_token %}
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/detail_publisher.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Просмотр издательства
{% endblock title %}
{% block body %}
    <h1>Просмотр издательства</h1>
    {{object.name}}
    <form action="" method="post">
        {% csrf_token %}
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/list_authors.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список авторов
{% endblock title %}
{% block body %}
<h1>Список авторов</h1>
<a href="{% url 'book_reference:author-create' %}">Добавить автора</a>
    <table class="table table-bordered">
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'book_reference:author-update' pk=obj.pk %}">{{obj.pk}}</a></td>
            <td>{{obj.name}}</td>
            <td><a href="{% url 'book_reference:author-delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-x-lg"></i></a></td>
        </tr>
        {% endfor %}  
    </table>
{% endblock body %}

src/book_reference/templates/book_reference/list_genres.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список жанров
{% endblock title %}
{% block body %}
    <h1>Список жанров</h1>
    <a href="{% url 'book_reference:genre-create' %}">Добавить жанр</a>
        <table class="table table-bordered">
            {% for obj in object_list %}
            <tr>
                <td><a href="{% url 'book_reference:genre-update' pk=obj.pk %}">{{obj.pk}}</a></td>
                <td>{{obj.name}}</td>
                <td><a href="{% url 'book_reference:genre-delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-x-lg"></a></td>
            </tr>
            {% endfor %}  
        </table>
{% endblock body %}

src/book_reference/templates/book_reference/list_publishers.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список издательств
{% endblock title %}
{% block body %}
    <h1>Список издательств</h1>
    <a href="{% url 'book_reference:publisher-create' %}">Добавить издательство</a>
    <table class="table table-bordered">
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'book_reference:publisher-update' pk=obj.pk %}">{{obj.pk}}</a></td>
            <td>{{obj.name}}</td>
            <td><a href="{% url 'book_reference:publisher-delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-x-lg"></i></a></td>
        </tr>
        {% endfor %}  
    </table>
{% endblock body %}

src/book_reference/templates/book_reference/list_series_all.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список серий
{% endblock title %}
{% block body %}
    <h1>Список серий</h1>
    <a href="{% url 'book_reference:series-create' %}">Добавить серию</a>
    <table class="table table-bordered">
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'book_reference:series-update' pk=obj.pk %}">{{obj.pk}}</a></td>
            <td>{{obj.name}}</td>
            <td><a href="{% url 'book_reference:series-delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-x-lg"></i></a></td>
        </tr>
        {% endfor %}  
    </table>
{% endblock body %}

src/book_reference/templates/book_reference/update_genre.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Обновление книжного жанра
{% endblock title %}
{% block body %}
    <h1>Обновление книжного жанра</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/update_publisher.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Обновление издательства
{% endblock title %}
{% block body %}
    <h1>Обновление издательства</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value="Submit">
    </form>
{% endblock body %}

src/book_reference/templates/book_reference/update_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Обновление серии
{% endblock title %}
{% block body %}
    <h1>Обновление серии</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value="Submit">
    </form>
{% endblock body %}