src/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
 
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('all/',views.ShowProfiles.as_view() , name='all-profiles'),
    path('customers/',views.ShowCustomers.as_view() , name='all-customers'),
    path('managers/',views.ShowManagers.as_view() , name='all-managers'),
    path('profile-update/<int:pk>/', views.UpdateProfiles.as_view(), name='profile-update'),
    path('profile-show/<int:pk>/', views.ShowProfile.as_view(), name='profile-detail'),
]

src/book/urls.py
from django.urls import path
from . import views
app_name = 'book'
urlpatterns = [
    path('show/<int:pk>/', views.ShowBook.as_view(), name='book-detail'),
    path('add_book_comment/<int:pk>/', views.CreateBookComments.as_view(), name='book-comment'),
    path('list_book_comment/', views.ShowComments.as_view(), name='book-comment-list'),
    path('update_book_comment/<int:pk>/', views.UpdateBookComments.as_view(), name='book-comment-update'),
    path('delete_book_comment/<int:pk>/', views.DeleteBookComments.as_view(), name='book-comment-delete'),
    path('all/', views.ShowBooks.as_view(), name='book-list'),
    path('add_book/', views.CreateBook.as_view(), name='book-add'),
    path('update_book/<int:pk>/', views.UpdateBook.as_view(), name='book-update'),
    path('add_book_csv/', views.upload_file, name='book-add-csv'), 
]

src/catalog/urls.py
from django.urls import path
from . import views
app_name = 'catalog'
urlpatterns = [
    path('',views.Catalogs.as_view(), name='catalog'),
    path('<int:pk>/',views.Catalog.as_view(), name='catalogs')
]

src/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('cart', views.show_cart, name='show-cart'),
    path('del-position/<int:pk>/', views.DelPosition.as_view(), name='del-position'),
    path('create-order/', views.Order.as_view(), name='create-order'),
    path('success/<int:pk>/', views.OrderSuccess.as_view(), name='order-success'),
    path('all/', views.OrdersAll.as_view(), name='list-orders'),
    path('current/', views.OrdersUser.as_view(), name='orders-user'),
    path('update/<int:pk>/', views.OrderUpdate.as_view(), name='order-update'),
    path('update-com/<int:pk>/', views.OrderCommentUpdate.as_view(), name='com-update'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name='order-detail'),
    path('delete/<int:pk>/', views.OrderDelete.as_view(), name='order-delete'),     
]

src/proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from catalog import views as c_views

urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('refs/', include('book_reference.urls', namespace='book_reference')),
    path('order/', include('orders.urls', namespace='orders')),
    path('',views.HomePage.as_view(), name='home-page'),
    path('catalog/',include('catalog.urls', namespace='catalog')),
    path('delivery/',views.Delivery.as_view(), name='delivery'),
    path('payment/',views.Payment.as_view(), name='payment'),
    path('contacts/',views.Contacts.as_view(), name='contacts'),
    path('search/', c_views.Search.as_view(template_name='catalog/search.html'), name='search'),
    path('book/', include('book.urls', namespace='book')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin-portal/', views.AdminPortal.as_view(),name='adm-portsl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/book/models.py
from distutils.command.upload import upload
from pyexpat import model
from random import choices
from re import T
from django import forms
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth import get_user_model
from django.db.models import Avg


User = get_user_model()
class Book(models.Model):
    book_title=models.CharField(
        max_length=40,
        verbose_name='Название книги'   
    )
    book_cover_photo=models.ImageField(
        verbose_name='Фото обложки',
        upload_to='upload'
    )
    book_genre=models.ManyToManyField(
        'book_reference.BookGenre',
        verbose_name='Жанр',
    )
    book_publisher=models.ForeignKey(
        'book_reference.BookPublisher',
        verbose_name='Издательство',
        on_delete=models.PROTECT,
    )
    book_series=models.ForeignKey(
        'book_reference.BookSeries',
        verbose_name='Серия',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )    
    book_author=models.ManyToManyField(
        'book_reference.BookAuthor',
        verbose_name='Автор',
    )
    book_price=models.DecimalField(
        max_digits=7,
        decimal_places=2,
        verbose_name='Цена (BYN)'
    )
    book_year=models. IntegerField(
        verbose_name='Год издания'
    )
    book_page=models.IntegerField(
        verbose_name='Страниц'
    )
    book_cover=models.CharField(
        max_length=30,
        verbose_name='Переплет'
    )
    book_format=models.CharField(
        max_length=40,
        verbose_name='Формат'
    )
    book_isbn=models.CharField(
        max_length=30,
        verbose_name='ISBN'
    )
    book_weight=models.PositiveIntegerField(
        verbose_name='Вес (гр)'
    )
    book_age=models.CharField(
        max_length=5,
        verbose_name='Возрастные ограничения'
    )
    book_count=models.PositiveIntegerField(
        verbose_name='Количество книг в наличии'
    )
    MY_CHOICES=[
        ('Yes', 'Да'),
        ('No', 'Нет'),
    ]   
    book_active=models.CharField (
        choices=MY_CHOICES,
        default='Да',
        max_length=10, 
        verbose_name='Активный (доступен для заказа)'
    )      
    book_rating=models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(10.0)],
        verbose_name='Рейтинг (0 - 10)'
    )
    book_date=models.DateField(
        auto_now_add=True,
        verbose_name='Дата внесения в каталог'
    )    
    book_date_change=models.DateField(
        auto_now=True,
        verbose_name='Дата последнего изменения карточки'
    )
    book_title_lower=models.CharField(
        max_length=40,
        verbose_name='Название книги',
        editable=False,
        null=True,
        blank=True   
    )

    def __str__(self):
        return self.book_title
    
    def save(self, *args, **kwargs):
        self.book_title_lower=self.book_title.lower() if self.book_title else None
        return super().save(*args, **kwargs)

    @property
    def average_rating(self):
        return self.b_comments.all().aggregate(Avg('rating'))['rating__avg']   


class BookComments(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='b_comments')
    customer = models.ForeignKey(User, on_delete=models.PROTECT, related_name='b_comments')
    comment = models.TextField()
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    created_date = models.DateField(auto_now=False, auto_now_add=True)
    updated_date = models.DateField(auto_now=True, auto_now_add=False)
    class Meta:
        db_table = 'BookCommentV2'
        ordering = ['-id']
    def __str__(self):
        return str(self.pk)      

src/book/forms.py
from django import forms
from .models import BookComments, Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'book_title',
            'book_cover_photo',
            'book_genre',
            'book_publisher',
            'book_series',
            'book_author',
            'book_price',
            'book_year',
            'book_page',
            'book_cover',
            'book_format',
            'book_isbn',
            'book_weight',
            'book_age',
            'book_count',
            'book_active',
            ]

class BookCommentsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.book_pk = kwargs.pop('book_pk')
        super(BookCommentsForm, self).__init__(*args, **kwargs)

    class Meta:
        model = BookComments
        fields = [
            'rating',
            'comment']

    def clean(self):
        if BookComments.objects.filter(customer=self.user, book__pk=self.book_pk).count() > 0:
            raise forms.ValidationError("Пользователь уже имеет комментарий")

        return super().clean()

class UploadFileForm(forms.Form):
    file = forms.FileField()

class BookCommentsFormUpdate(forms.ModelForm):
    class Meta:
        model = BookComments
        fields = [
            'rating',
            'comment']

src/book/views.py
from django.views import generic
from . import models,forms
from book_reference import models as b_models
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from home_page.views import BaseTemplatePageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin


class ShowBook(BaseTemplatePageMixin, generic.DetailView):
    model = models.Book
    template_name = 'book/detail_book.html'

class CreateBookComments(BaseTemplatePageMixin, LoginRequiredMixin, generic.CreateView):
    model = models.BookComments
    login_url = reverse_lazy('login')
    form_class = forms.BookCommentsForm
    template_name = 'book/create_book_comment.html'

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw['user'] = self.request.user
        kw['book_pk'] = self.kwargs.get('pk')
        return kw

    def form_valid(self, form):
        book_pk = self.kwargs.get('pk')
        book = models.Book.objects.get(pk=book_pk)
        form.instance.book = book
        form.instance.customer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('book:book-detail', kwargs={'pk': self.object.book.pk})

class ShowComments(BaseTemplatePageMixin, generic.ListView):
    paginate_by = 7
    model = models.BookComments
    template_name = 'book/comments_list.html'
    class Meta:
        ordering = ['-id']
    def get_queryset(self): 
        qs = super().get_queryset() 
        if 'search' in self.request.GET:
            search=self.request.GET['search']
            return qs.filter(comment__icontains=search)
        else:
            return qs

# class SearchCom(BaseTemplatePageMixin, generic.TemplateView):
#     template_name='book/search_com.html'
#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(*args,**kwargs)
#         search=self.request.GET['search']
#         context['search_c'] = models.BookComments.objects.filter(comment__icontains=search
#         )
#         return context  

class UpdateBookComments(BaseTemplatePageMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.BookComments
    form_class = forms.BookCommentsFormUpdate
    template_name = 'book/update_book_comment.html'
    login_url = reverse_lazy('login')
    def get_success_url(self):
        return reverse_lazy('book:book-detail', kwargs={'pk': self.object.book.pk})        


class DeleteBookComments(BaseTemplatePageMixin, LoginRequiredMixin, generic.DeleteView):
    model = models.BookComments
    template_name = 'book/delete_book_comment.html'
    login_url = reverse_lazy('login')
    def get_success_url(self):
        return reverse_lazy('book:book-detail', kwargs={'pk': self.object.book.pk})

class ShowBooks(BaseTemplatePageMixin, generic.ListView):
    model = models.Book
    template_name = 'book/book_list.html'

class CreateBook(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin, generic.CreateView):
    model = models.Book
    form_class = forms.BookForm
    template_name = 'book/create_book.html'
    permission_required = ("book.add_book")
    login_url = reverse_lazy('login')
    def get_success_url(self):
        return reverse_lazy('book:book-detail', kwargs={'pk': self.object.pk})


class UpdateBook(BaseTemplatePageMixin, PermissionRequiredMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.Book
    form_class = forms.BookForm
    template_name = 'book/update_book.html'
    permission_required = ("book.change_book")
    login_url = reverse_lazy('login')
    def get_success_url(self):
        return reverse_lazy('book:book-detail', kwargs={'pk': self.object.pk})


def handle_uploaded_file(f):
    file_content = f.read().decode("utf-8")
    for line in file_content.split('\n'):
        fields = line.split(',')
        book = models.Book(
            book_title=fields[0],
            book_cover_photo=fields[1],
            book_publisher=b_models.BookPublisher.objects.get(pk=int(fields[3])),
            book_series=b_models.BookSeries.objects.get(pk=int(fields[4])),            
            book_price=float(fields[6]),
            book_year=int(fields[7]),
            book_page=int(fields[8]),
            book_cover=fields[9],
            book_format=fields[10],
            book_isbn=fields[11],
            book_weight=int(fields[12]),
            book_age=fields[13],
            book_count=int(fields[14]),
            book_active=fields[15],
            book_rating=float(fields[16]),
        )
        book.save()
        book.book_genre.add(b_models.BookGenre.objects.get(pk=int(fields[2])))
        book.book_author.add(b_models.BookAuthor.objects.get(pk=int(fields[5])))

def upload_file(request):
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return redirect('home-page')
    else:
        form = forms.UploadFileForm()
    return render(request, 'book/create_book_cvs.html', {'form': form})

src/book/templates/book/book_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список книг
{% endblock title %}
{% block body %}
    <h1>Список книг</h1>
        <a href="{% url 'book:book-add' %}">Добавать книгу</a> | <a href="{% url 'book:book-add-csv' %}">Добавать книгу из csv-файла</a>
        <table class="table table-bordered">
            <tr>
                <td><b>Название</b></td>
                <td><b>Авторы</b></td>
                <td><b>Жанры</b></td>
                <td><b>Издательство</b></td>
                <td><b>Серия</b></td>
                <td><b>Год издания</b></td>
                <td><b>Активный</b></td>
                <td><b>Стоимость</b></td>
            </tr>
            {% for obj in object_list %}
            <tr>
                <td><a href="{% url 'book:book-update' pk=obj.pk %}">{{obj.book_title}}</a></td>
                <td>{% for author in obj.book_author.values_list %} {{author.1}} {% endfor %}</td>
                <td>{% for genre in obj.book_genre.values_list %} {{genre.1}} {% endfor %}</td>
                <td>{{obj.book_publisher}}</td>
                <td>{{obj.book_series}}</td>
                <td>{{obj.book_year}}</td>
                <td>{{obj.book_active}}</td>
                <td>{{obj.book_price}} руб.</td>
            </tr>       
            {% endfor %}  
        </table> 
{% endblock body %}

src/book/templates/book/comments_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список комментариев
{% endblock title %}
{% block body %}
    <h1 style="text-align:center">Список комментариев</h1>
    <form class="d-flex" role="search" method="get" action="">
        <input name="search" class="form-control me-1" type="search" placeholder="Поиск по комментариям" aria-label="Поиск" style="min-width: max-content;">
        <button class="btn btn-outline-light" type="submit">Поиск</button>
      </form> 
    <table class="table table-bordered">
        <tr>
            <td><strong>Книга</strong></td>
            <td><strong>Комментарий</strong></td>
            <td><strong>Оценка</strong></td>
            <td><strong>Дата</strong></td>
            <td><strong>Пользователь</strong></td>        
        </tr>
        {% for obj in object_list %}
        <tr>          
            <td><a href="{% url 'book:book-detail' pk=obj.pk %}">{{obj.book}}</a></td>            
            <td>{{obj.comment}}</td>
            <td>{{obj.rating}}</td> 
            <td>{{obj.updated_date}}</td>
            <td>{{obj.customer}}</td>
        </tr>
        {% endfor %}  
    </table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Пердыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock body %}

src/book/templates/book/create_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Создание книги</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}

src/book/templates/book/create_book_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Создание комментария</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}

src/book/templates/book/create_book_cvs.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Добавить книгу</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}

src/book/templates/book/delete_book_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Удаление издательства
{% endblock title %}
{% block body %}
    <h1>Удаление комментария</h1>
    {{object.comment}}<br>
    Рейтинг:{{object.rating}}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Submit">
    </form>
{% endblock body %}

src/book/templates/book/detail_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Просмотр товара
{% endblock title %}
{% block body %}
    <h1>Просмотр товара</h1>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <img style="max-width: 100%;" src="{{ object.book_cover_photo.url }}" />
            </div>
            <div class="col-8">
              <h2>{{ object.book_title }}</h2>  
              <div>
                Жанры : {% for genre in object.book_genre.all %} <a href="{% url 'catalog:catalogs' pk=genre.pk %}">{{ genre.name }}</a> {% endfor %}
              </div>          
              <div>
                Авторы: {% for author in object.book_author.values_list %}{{author.1}}  {% endfor %}
              </div>
              <div>
                Издательство: {{object.book_publisher}} 
              </div>
              <div>
                Серия: {{object.book_series}} 
              </div>
              <div>
                Цена: {{object.book_price}} руб. 
              </div>
              <div>
                Год изднания: {{object.book_year}} 
              </div>
              <div>
                Колличество страниц: {{object.book_page}} 
              </div>
              <div>
                Переплет: {{object.book_cover}} 
              </div>
              <div>
                Формат: {{object.book_format}} 
              </div>
              <div>
                ISBN: {{object.book_isbn}} 
              </div>
              <div>
                Вес: {{object.book_weight}} гр.
              </div>
              <div>
                Возрастные ограничения: {{object.book_age}}
              </div>
              <div>
                Рейтинг: {{object.average_rating|default_if_none:"Оценки отсутствуют"}}
              </div>
              <div>{% for group in request.user.groups.all %}{% if group.name == 'Customers' %}
                <form action='{% url 'orders:show-cart' %}' method="post">
                  {% csrf_token %}
                  <input type="number" name="quantity" id="" value="1" step="1" min="1"  width="min"><br>
                  <input type="hidden" name="book_pk" value={{book.pk}}>
                  <button type="submit" class="btn btn-primary mt-auto">Добавить в корзину</button>
                </form>
              </div>{% endif %}{% endfor %}
              {% if user.is_authenticated != True %}
                <div>
                  <form action='{% url 'orders:show-cart' %}' method="post">
                    {% csrf_token %}
                    <input type="number" name="quantity" id="" value="1" step="1" min="1"  width="min"><br>
                    <input type="hidden" name="book_pk" value={{book.pk}}>
                    <button type="submit" class="btn btn-primary mt-auto">Добавить в корзину</button>
                  </form>
                </div>{% else %}
                <div><br>
                  <a href="{% url 'book:book-comment' pk=book.pk %}">Добавить комментарий</a>
                </div>{% endif %}
            </div>
          </div>
    </div>
    <br>
    <h3>Отзывы на товар</h3>
    {% for com in object.b_comments.all%}
      <table class="table table-bordered">
        <tr>
          <td>
            {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile-detail' pk=com.customer.profile.pk %}">{{com.customer}}</a> {{com.updated_date}}<br>
            {% else %}
            <b>{{com.customer}}</b> {{com.updated_date}}<br>
            {% endif %}
            Оценка: {{com.rating}}<br>
            Комментарий: {{com.comment}}<br>
            {% if request.user.username == com.customer.username%}
            <a href="{% url 'book:book-comment-update' pk=com.pk %}">Изменить</a>  |  
            <a href="{% url 'book:book-comment-delete' pk=com.pk %}">Удалить</a>
            {% endif %}
          </td>
        </tr>
      </table>
    {% endfor %}    
{% endblock body %}

src/book/templates/book/update_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Редактировать книгу</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}

src/book/templates/book/update_book_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Изменение комментария</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}