src/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
 
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('all/',views.ShowProfiles.as_view() , name='all-profiles'),
    path('customers/',views.ShowCustomers.as_view() , name='all-customers'),
    path('managers/',views.ShowManagers.as_view() , name='all-managers'),
    path('profile-update/<int:pk>/', views.UpdateProfiles.as_view(), name='profile-update'),
    path('profile-show/<int:pk>/', views.ShowProfile.as_view(), name='profile-detail'),
]

src/book/urls.py
from django.urls import path
from . import views
app_name = 'book'
urlpatterns = [
    path('show/<int:pk>/', views.ShowBook.as_view(), name='book-detail'),
    path('add_book_comment/<int:pk>/', views.CreateBookComments.as_view(), name='book-comment'),
    path('list_book_comment/', views.ShowComments.as_view(), name='book-comment-list'),
    path('update_book_comment/<int:pk>/', views.UpdateBookComments.as_view(), name='book-comment-update'),
    path('delete_book_comment/<int:pk>/', views.DeleteBookComments.as_view(), name='book-comment-delete'),
    path('all/', views.ShowBooks.as_view(), name='book-list'),
    path('add_book/', views.CreateBook.as_view(), name='book-add'),
    path('update_book/<int:pk>/', views.UpdateBook.as_view(), name='book-update'),
    path('add_book_csv/', views.upload_file, name='book-add-csv'), 
]

src/book_reference/urls.py
from django.urls import path
from . import views
app_name = 'book_reference'
urlpatterns = [
    path('genre-create/', views.CreateGenre.as_view(), name='genre-create'),
    path('genre-update/<int:pk>/', views.UpdateGenre.as_view(), name='genre-update'),
    path('genre-delete/<int:pk>/', views.DeleteGenre.as_view(), name='genre-delete'),
    path('genre-show/<int:pk>/', views.ShowGenre.as_view(), name='genre-detail'),
    path('genres-show/', views.ShowGenres.as_view(), name='genre-list'),
    path('author-create/', views.CreateAuthor.as_view(), name='author-create'),
    path('author-update/<int:pk>/', views.UpdateAuthor.as_view(), name='author-update'),
    path('author-delete/<int:pk>/', views.DeleteAuthor.as_view(), name='author-delete'),
    path('author-show/<int:pk>/', views.ShowAuthor.as_view(), name='author-detail'),
    path('authors-show/', views.ShowAuthors.as_view(), name='author-list'),
    path('publisher-create/', views.CreatePublisher.as_view(), name='publisher-create'),
    path('publisher-update/<int:pk>/', views.UpdatePublisher.as_view(), name='publisher-update'),
    path('publisher-delete/<int:pk>/', views.DeletePublisher.as_view(), name='publisher-delete'),
    path('publisher-show/<int:pk>/', views.ShowPublisher.as_view(), name='publisher-detail'),
    path('publishers-show/', views.ShowPublishers.as_view(), name='publisher-list'),
    path('series-create/', views.CreateSeries.as_view(), name='series-create'),
    path('series-update/<int:pk>/', views.UpdateSeries.as_view(), name='series-update'),
    path('series-delete/<int:pk>/', views.DeleteSeries.as_view(), name='series-delete'),
    path('series-show/<int:pk>/', views.ShowSeries.as_view(), name='series-detail'),
    path('series-all-show/', views.ShowSeriesAll.as_view(), name='series-list'),
]

src/catalog/urls.py
from django.urls import path
from . import views
app_name = 'catalog'
urlpatterns = [
    path('',views.Catalogs.as_view(), name='catalog'),
    path('<int:pk>/',views.Catalog.as_view(), name='catalogs')
]

src/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('cart', views.show_cart, name='show-cart'),
    path('del-position/<int:pk>/', views.DelPosition.as_view(), name='del-position'),
    path('create-order/', views.Order.as_view(), name='create-order'),
    path('success/<int:pk>/', views.OrderSuccess.as_view(), name='order-success'),
    path('all/', views.OrdersAll.as_view(), name='list-orders'),
    path('current/', views.OrdersUser.as_view(), name='orders-user'),
    path('update/<int:pk>/', views.OrderUpdate.as_view(), name='order-update'),
    path('update-com/<int:pk>/', views.OrderCommentUpdate.as_view(), name='com-update'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name='order-detail'),
    path('delete/<int:pk>/', views.OrderDelete.as_view(), name='order-delete'),     
]

src/proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from catalog import views as c_views

urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('refs/', include('book_reference.urls', namespace='book_reference')),
    path('order/', include('orders.urls', namespace='orders')),
    path('',views.HomePage.as_view(), name='home-page'),
    path('catalog/',include('catalog.urls', namespace='catalog')),
    path('delivery/',views.Delivery.as_view(), name='delivery'),
    path('payment/',views.Payment.as_view(), name='payment'),
    path('contacts/',views.Contacts.as_view(), name='contacts'),
    path('search/', c_views.Search.as_view(template_name='catalog/search.html'), name='search'),
    path('book/', include('book.urls', namespace='book')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin-portal/', views.AdminPortal.as_view(),name='adm-portsl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/home_page/views.py
from django.shortcuts import render
from django.views import generic
from book import models as b_models
from book_reference import models
import requests
import time
# Create your views here.

class BaseTemplatePageMixin:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['current_genre_all'] = models.BookGenre.objects.all()

        current_time_in_seconds = time.time()
        one_day_in_seconds = 60*60*24
        currency_rate = self.request.session.get('currency_rate', None)
        currency_rate_updated = self.request.session.get('currency_rate_updated', current_time_in_seconds)

        if not currency_rate or (current_time_in_seconds - currency_rate_updated) > one_day_in_seconds:
            try:
                headers = {'Accept': 'application/json'}
                r = requests.get('https://www.nbrb.by/api/exrates/rates/431', headers=headers, timeout=1)
                currency_object = r.json()
                currency_rate = currency_object['Cur_OfficialRate']
            except:
                currency_rate = 2.5
                
            self.request.session['currency_rate'] = currency_rate
            self.request.session['currency_rate_updated'] = time.time()

        context['currency'] = currency_rate
        return context

class HomePage(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/home_page.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['new_book'] = b_models.Book.objects.order_by('-book_date')
        context['best_book'] = b_models.Book.objects.order_by('book_rating')
        context['ref_book'] = b_models.Book.objects.order_by('book_count')
        return context

class Delivery(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/delivery.html'


class Payment(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/payment.html'

class Contacts(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/contacts.html'

class AdminPortal(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/admin_portal.html'

src/home_page/templates/home_page/admin_portal.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
<br>
   <h2 align="center">Административный портал</h2><br>
   <div class="row row-cols-4 row-cols-md-4 g-4">
      <div class="col">
         <div class="card h-100 w=75 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Заказы</h5>
               <a href="{% url 'orders:list-orders' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Пользователи</h5>
               <a href="{% url 'accounts:all-profiles' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Книги</h5>
               <a href="{% url 'book:book-list' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Жанры</h5>
               <a href="{% url 'book_reference:genre-list' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Авторы</h5>
               <a href="{% url 'book_reference:author-list' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Серии</h5>
               <a href="{% url 'book_reference:series-list' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Издательства</h5>
               <a href="{% url 'book_reference:publisher-list' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card h-100 border-secondary" style="width: 18rem;" >
            <div class="card-body">
               <h5 class="card-title" style="text-align:center"><i class="bi bi-pencil"></i></h5>
               <h5 class="card-title" style="text-align:center">Комментарии</h5>
               <a href="{% url 'book:book-comment-list' %}" class="btn btn-primary" style="display: block; margin: 0 auto;">Перейти в раздел</a>
            </div>
         </div>
      </div>     
   </div>
{% endblock body %}      
       

src/home_page/templates/home_page/book_card.html
<div class="col">
    <div class="card h-100" style="width: 15rem;">
        <a href="{% url 'book:book-detail' pk=book.pk %}" class="h-50 w-50 mx-auto">
          <img src="{{ book.book_cover_photo.url }}" class="card-img-top">
        </a>
        <div class="card-body d-flex flex-column text-center">
          <h5 class="card-title">{{book.book_title}}</h5>
          <p class="card-text">{% for author in book.book_author.values_list %} {{author.1}} {% endfor %}</p>
          <p class="card-text">{{book.book_price}} руб.</p>
          <a href="{% url 'book:book-detail' pk=book.pk %}" class="btn btn-primary mt-auto">Просмотреть товар</a>
        </div>
    </div>
  </div> 

src/home_page/templates/home_page/contacts.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
   <h2 align="center">Контакты</h2>   
      <h5>Телефоны</h5>
      <p>8 (017) 399-73-80<br>
         8 (017) 396-47-72<br>
         8 (029) 606-85-85</p>
      <h5>E-mail</h5>
      <a href="mailto:office@chtetz.by">office@chtetz.by</a><br>
      <a href="mailto:torgotdel@chtetz.by">torgotdel@chtetz.by</a><br>
      <a href="mailto:bkmag_5@chtetz.by">bkmag_5@chtetz.by</a><br>
      <h5>Режим работы</h5>
      <p>Понедельник - пятница: 8:30-20:30<br>
         Суббота - воскресенье: 8:30-18:30</p>
      <h5>Руководство ОАО «Чтец»</h5>
      <p>Генеральный директор: Матусевич Владимир Владимирович<br>
         +375 (17) 394-89-45<br>
         E-mail <a href="mailto:matusevich@chtetz.by">matusevich@chtetz.by</a></p>
      <p>Первый заместитель генерального директора: Силинский Геннадий Анатольевич<br>
         +375 (17) 394-89-59<br>
         E-mail <a href="mailto:silinsky@chtetz.by">silinsky@chtetz.by</a></p>      
{% endblock body %}        

src/home_page/templates/home_page/delivery.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
        <h2 align="center">Доставка</h2>   
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Доставка</li>
          </ol>
        </nav>
        <h3>
          Бесконтактная доставка </h3>
          <p>
             Чтобы воспользоваться данной услугой необходимо:
          </p>
          <p>
             1. При оформлении заказа на сайте выбрать оплату в системе ЕРИП , в&nbsp;комментариях покупателя написать - Бесконтактная доставка.
          </p>
          <p>
             2. Наш менеджер с Вами свяжется для уточнения времени доставки. После выставит счет для оплаты в системе ЕРИП.
          </p>
          <p>
             3. Оплачиваете заказ и ждете курьера!
          </p>
          <h3>
          Курьером по Минску </h3>
          <p>
             Доставка осуществляется с 16.00 до 20.00<br>
             Доставка курьером по Минску осуществляется в пределах МКАД. Доставка курьером по Минску осуществляется для заказов стоимостью свыше 20 рублей. Для заказов стоимостью свыше 70 рублей доставка курьером осуществляется бесплатно. Для заказов стоимостью от 20 до 70 рублей стоимость доставки курьером 5 рублей.&nbsp;
          </p>
          <p>
             Форма оплаты - наличный расчет или через систему ЕРИП. Указание точного адреса доставки и контактного телефона обязательно. Перед тем, как доставить заказ, курьер обязан предварительно созвониться с Вами для уточнения времени доставки. Доставка курьером по Минску осуществляется в пределах МКАД.&nbsp; Доставка курьером по Минску осуществляется для заказов стоимостью свыше 20 рублей.&nbsp;
          </p>
          <p>
             Для заказов стоимостью свыше 70 рублей доставка курьером осуществляется бесплатно. Для заказов стоимостью от 20 до 70 рублей стоимость доставки курьером 5 рублей. Форма оплаты - наличный расчет или через систему ЕРИП. Указание точного адреса доставки и контактного телефона обязательно. Перед тем, как доставить заказ, курьер обязан предварительно созвониться с Вами для уточнения времени доставки.
          </p>
          <p>
          </p>
          <h3>Почтой по Республике Беларусь&nbsp;</h3>
          <p>
             После получения Вашего заказа с Вами свяжется&nbsp;представитель интернет-магазина, а затем на электронный ящик, указанный в заказе, будет выслана счет-фактура на оплату. Оплата по счет-фактуре производится в ближайшем отделении банка, с помощью системы&nbsp;интернет-банкинга либо в почтовом отделении.&nbsp;
          </p>
          <p>
             Сумма оплаты включает: стоимость заказанных вами товаров + стоимость упаковочного и стоимость обработки заказа 1 рубль 62 копейки с НДС + стоимость пересылки согласно тарифам &nbsp;<a rel="nofollow" href="http://www.belpost.by/" target="_blank" title="Ссылка: http://www.belpost.by/">РУП «Белпочта»</a>&nbsp;(в зависимости от веса товара) от 3,00 рублей.
          </p>
          <p>
             Срок оплаты счёт-фактур - 10 банковских дней с момента выставления счёта. После этого срока неоплаченный заказ будет аннулирован (для продления срока оплаты необходимо обратиться в интернет-магазин).
          </p>
          <p>
             Заказ высылается почтой на Ваш&nbsp;адрес после того, как мы получим подтверждение его оплаты. Оплата от физических лиц поступает на расчетный счет магазина в течение 2-3 рабочих дней.
          </p>
          <h3>Самовывоз&nbsp;</h3>
          <p>
             После комплектации заказа Вам надо будет самостоятельно забрать его в течение 10&nbsp;дней в любом из&nbsp;<a href="https://belkniga.by/contacts/stores/">магазинов сети Чтец.</a><br>
           <br>
             Мы сообщим Вам о наличии заказа в пункте выдачи с помощью электронной почты,SMS или телефона. Услуга бесплатная.&nbsp;<br>
           <br>
             Форма оплаты – наличный и безналичный расчет, по пластиковым карточкам или в системе ЕРИП.
          </p>
{% endblock body %}        

src/home_page/templates/home_page/home_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
<!-- <h1 align="center">Home page</h1> -->
  <div class="container text-center">
    <div class="row">
      <div class="col-4">
        <div class="list-group list-group-flush">
          <a href="/catalog" class="list-group-item list-group-item-danger" ><h5><i class="bi bi-caret-down"></i> Каталог</h5></a>
          {% for obj in current_genre_all %}
          <a href="{% url 'catalog:catalogs' pk=obj.pk %}" class="list-group-item list-group-item-action">{{obj.name}}</a>
          {% endfor %} 
        </div>
      </div>  
      <div class="col-8">
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleDark"  data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="10000">
              <img src="..\..\media\upload\ПОДАРОК.jpg" class="rounded mx-auto d-block w-100"  alt="..."  >
              <div class="carousel-caption d-none d-md-block">
                <h5>Книга в подарок</h5>
                <p>за первый товар с регистрацией!</p>
              </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="..\..\media\upload\СЕРТИФИКАТ.png" class="rounded mx-auto d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h7>Приобрести подарочнный сертификат</h7>
                <!-- <p>Подарок, с которым всегда угадаешь!</p> -->
              </div>
            </div>
            <div class="carousel-item">
              <img src="..\..\media\upload\ДОСТАВКА.png" class="rounded mx-auto d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h5>Бесплатная доставка товаров</h5>
                <p>для заказов стоимостью свыше 25 рублей</p>
              </div>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <br>
      </div> 
      <br>
      <h5 align="center">Новинки</h5>   
      <div class="row row-cols-1 row-cols-md-5 g-2">
        {% for obj in new_book %}
        {% include "home_page/book_card.html" with book=obj %}        
        {% endfor %}  
        </div>
        <br>
        <h5 align="center">Наиболее популярные</h5>
        <div class="row row-cols-1 row-cols-md-5 g-2">
          {% for obj in best_book %}
          {% include "home_page/book_card.html" with book=obj %}        
          {% endfor %}  
        </div>  
        <br>
        <h5 align="center">Рекомендуем</h5>
        <div class="row row-cols-1 row-cols-md-5 g-2">
          {% for obj in ref_book %}
          {% include "home_page/book_card.html" with book=obj %} 
          {% endfor %}  
        </div>  
{% endblock body %}

src/home_page/templates/home_page/payment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
        <h2 align="center">Оплата</h2>   
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Оплата</li>
          </ol>
        </nav>
        <h3>
         Бесконтактная доставка </h3>
         <p>
             Чтобы воспользоваться данной услугой необходимо:
         </p>
         <p>
             1. При оформлении заказа на сайте выбрать оплату в системе ЕРИП , в&nbsp;комментариях покупателя написать - Бесконтактная доставка.
         </p>
         <p>
             2. Наш менеджер с Вами свяжется для уточнения времени доставки. После выставит счет для оплаты в системе ЕРИП.
         </p>
         <p>
             3. Оплачиваете заказ и ждете курьера!
         </p>
         <h3>
         Курьером по Минску </h3>
         <p>
             Доставка осуществляется с 12.00 до 20.00<br>
             Доставка курьером по Минску осуществляется в пределах МКАД. Доставка курьером по Минску осуществляется для заказов стоимостью свыше 20 рублей. Для заказов стоимостью свыше 70 рублей доставка курьером осуществляется бесплатно. Для заказов стоимостью от 20 до 70 рублей стоимость доставки курьером 5 рублей.&nbsp;
         </p>
         <p>
             Форма оплаты - наличный расчет или через систему ЕРИП. Указание точного адреса доставки и контактного телефона обязательно. Перед тем, как доставить заказ, курьер обязан предварительно созвониться с Вами для уточнения времени доставки. Доставка курьером по Минску осуществляется в пределах МКАД.&nbsp; Доставка курьером по Минску осуществляется для заказов стоимостью свыше 15 рублей.&nbsp;
         </p>
         <p>
             Для заказов стоимостью свыше 25 рублей доставка курьером осуществляется бесплатно. Для заказов стоимостью от 15 до 25 рублей стоимость доставки курьером 5 рублей. Форма оплаты - наличный расчет или через систему ЕРИП. Указание точного адреса доставки и контактного телефона обязательно. Перед тем, как доставить заказ, курьер обязан предварительно созвониться с Вами для уточнения времени доставки.
         </p>
         <p>
         </p>
         <h3>Наличный расчет</h3>
         <p>
             Вы расплачиваетесь наличными деньгами в момент получения заказа, после проверки комплектности и качества товара. Эта форма оплаты используется для доставки курьером и в случае самовывоза.
         </p>
         <h3>Почтовый перевод</h3>
         <p>
             После получения вашего заказа на электронный ящик, указанный в заказе, будет выслана счет-фактура на оплату.&nbsp;Оплата по счет-фактуре производится в ближайшем отделении банка, с помощью системы&nbsp;интернет-банкинга, либо в почтовом отделении.&nbsp;<br>
          <br>
             Сумма оплаты включает: стоимость заказанных вами товаров + стоимость упаковки и обработки заказа 1рубль 62 копейки с НДС + стоимость пересылки согласно тарифам &nbsp;<a rel="nofollow" href="https://www.belpost.by/" target="_blank" title="Ссылка: http://www.belpost.by/">РУП «Белпочта»</a>&nbsp;(в зависимости от веса товара).&nbsp;<br>
          <br>
             Срок оплаты счёт-фактур - 10 банковских дней с момента выставления счёта. После этого срока неоплаченный заказ будет аннулирован (для продления срока оплаты необходимо обратиться в интернет-магазин).
         </p>
         <p>
             Заказ высылается почтой на Ваш адрес после того, как мы получим подтверждение его оплаты. Оплата от физических лиц поступает на расчетный счет магазина в течение 2-3 рабочих дней.
         </p>
         <h3>Банковская карта</h3>
         <p>
             Банковской пластиковой картой Вы можете оплатить свой заказ при самовывозе товара и при доставке курьером.
         </p>
         <h3>
         ЕРИП </h3>
         <p>
             Оплату Вы можете произвести в любом банке: интернет-банкинге, мобильном банкинге, инфокиоске, банкомате, кассе и т.д. Совершить оплату можно с использованием наличных денежных средств, любых электронных денег, банковских платежных карточек.
         </p>
         <h6>
         ДЛЯ ПРОВЕДЕНИЯ ПЛАТЕЖА НЕОБХОДИМО:</h6>
         <ol>
            <li>Выбрать последовательно пункты:</li>
            <ul>
               <li>Система "Расчет" (ЕРИП)</li>
               <li>Интернет-магазины/сервисы</li>
               <li>A-Z Латинские домены</li>
               <li>M</li>
               <li>Magazin.chtetz.by</li>
            </ul>
            <li>Для оплаты "Товара" ввести Номер заказа.</li>
            <li>Ввести сумму платежа (если не указана).</li>
            <li>Проверить корректность информации</li>
            <li>Совершить платеж.</li>
         </ol>
         <p>
             Если Вы осуществляете платеж в кассе банка, пожалуйста, сообщите кассиру о необходимости проведения платежа через систему ”Расчет“ (ЕРИП).
         </p>
         <p>
             Техническое взаимодействие с системой "Расчет" (ЕРИП) осуществляется с помощью сервиса «Экспресс Платежи» (<a rel="nofollow" href="https://express-pay.by/)">https://express-pay.by/)</a>.
         </p>
{% endblock body %}        