src/book/urls.py
from django.urls import path
from . import views
app_name = 'book'
urlpatterns = [
    path('show/<int:pk>/', views.ShowBook.as_view(), name='book-detail'),
    path('add_book_comment/<int:pk>/', views.CreateBookComments.as_view(), name='book-comment'),
    path('list_book_comment/', views.ShowComments.as_view(), name='book-comment-list'),
    path('update_book_comment/<int:pk>/', views.UpdateBookComments.as_view(), name='book-comment-update'),
    path('delete_book_comment/<int:pk>/', views.DeleteBookComments.as_view(), name='book-comment-delete'),
    path('all/', views.ShowBooks.as_view(), name='book-list'),
    path('add_book/', views.CreateBook.as_view(), name='book-add'),
    path('update_book/<int:pk>/', views.UpdateBook.as_view(), name='book-update'),
    path('add_book_csv/', views.upload_file, name='book-add-csv'), 
]

src/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('cart', views.show_cart, name='show-cart'),
    path('del-position/<int:pk>/', views.DelPosition.as_view(), name='del-position'),
    path('create-order/', views.Order.as_view(), name='create-order'),
    path('success/<int:pk>/', views.OrderSuccess.as_view(), name='order-success'),
    path('all/', views.OrdersAll.as_view(), name='list-orders'),
    path('current/', views.OrdersUser.as_view(), name='orders-user'),
    path('update/<int:pk>/', views.OrderUpdate.as_view(), name='order-update'),
    path('update-com/<int:pk>/', views.OrderCommentUpdate.as_view(), name='com-update'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name='order-detail'),
    path('delete/<int:pk>/', views.OrderDelete.as_view(), name='order-delete'),     
]

src/proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from catalog import views as c_views

urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('refs/', include('book_reference.urls', namespace='book_reference')),
    path('order/', include('orders.urls', namespace='orders')),
    path('',views.HomePage.as_view(), name='home-page'),
    path('catalog/',include('catalog.urls', namespace='catalog')),
    path('delivery/',views.Delivery.as_view(), name='delivery'),
    path('payment/',views.Payment.as_view(), name='payment'),
    path('contacts/',views.Contacts.as_view(), name='contacts'),
    path('search/', c_views.Search.as_view(template_name='catalog/search.html'), name='search'),
    path('book/', include('book.urls', namespace='book')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin-portal/', views.AdminPortal.as_view(),name='adm-portsl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

User = get_user_model()



class Cart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='carts',
        verbose_name='User Cart',
        null=True,
        blank=True,
    )
    def total_price(self):
        all_books_positions = self.books.all()
        total_price = 0
        for book_position in all_books_positions:
            total_price += book_position.price_per_position
        return total_price

class BookInCart(models.Model):
    book = models.ForeignKey(
        "book.Book",
        verbose_name='Book in a cart',
        on_delete=models.PROTECT)
    cart = models.ForeignKey(
        "orders.Cart",
        verbose_name='Cart',
        related_name='books',
        on_delete=models.PROTECT)
    quantity = models.IntegerField(
        verbose_name='Quantity',
        default=1)
    created_date = models.DateTimeField(
        'Created date',
        auto_now=False,
        auto_now_add=True)      
    updated_date = models.DateTimeField(
        'Updated date',
        auto_now=True,
        auto_now_add=False)


    @property    
    def price_per_position(self):
        return self.book.book_price * self.quantity
statuses=(
    ('Заказ принят', 'Заказ принят'),
    ('Заказ собран', 'Заказ собран'),
    ('Заказ отправлен', 'Заказ отправлен'),
    ('Заказ доставлен', 'Заказ доставлен'),    
)
class Order(models.Model):
    status = models.CharField(
        verbose_name='Статус',
        max_length=200,
        choices=statuses,
        default='Заказ принят'
    )
    cart = models.OneToOneField(
        "orders.Cart",
        verbose_name='Cart',
        related_name='order',
        on_delete=models.PROTECT)   
    last_first_name=models.CharField(
        max_length=200,
        verbose_name='Фамилия Имя:'
    )
    email=models.EmailField(
        max_length=200,
        verbose_name='E-mail:'
    )
    adress=models.CharField(
        max_length=200,
        verbose_name='Адрес достаки:'
    )
    phone_number=models.CharField(
        max_length=200,
        verbose_name='Номер телефона:'
    )
    information=models.TextField(
        verbose_name='Добавить комментарий к заказу:',
        null=True,
        blank=True,
    )
    created_date = models.DateTimeField(
        'Created date',
        auto_now=False,
        auto_now_add=True)      
    updated_date = models.DateTimeField(
        'Updated date',
        auto_now=True,
        auto_now_add=False)
    def get_absolute_url(self):
        return reverse_lazy('orders:order-success', kwargs={'pk':self.pk})        

src/orders/forms.py
from django import forms
from . import models

class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ('last_first_name','email','adress','phone_number','information')

class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ('status','cart','last_first_name','email','adress','phone_number','information')

class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ('information',)

src/home_page/views.py
from django.shortcuts import render
from django.views import generic
from book import models as b_models
from book_reference import models
import requests
import time
# Create your views here.

class BaseTemplatePageMixin:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['current_genre_all'] = models.BookGenre.objects.all()

        current_time_in_seconds = time.time()
        one_day_in_seconds = 60*60*24
        currency_rate = self.request.session.get('currency_rate', None)
        currency_rate_updated = self.request.session.get('currency_rate_updated', current_time_in_seconds)

        if not currency_rate or (current_time_in_seconds - currency_rate_updated) > one_day_in_seconds:
            try:
                headers = {'Accept': 'application/json'}
                r = requests.get('https://www.nbrb.by/api/exrates/rates/431', headers=headers, timeout=1)
                currency_object = r.json()
                currency_rate = currency_object['Cur_OfficialRate']
            except:
                currency_rate = 2.5
                
            self.request.session['currency_rate'] = currency_rate
            self.request.session['currency_rate_updated'] = time.time()

        context['currency'] = currency_rate
        return context

class HomePage(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/home_page.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['new_book'] = b_models.Book.objects.order_by('-book_date')
        context['best_book'] = b_models.Book.objects.order_by('book_rating')
        context['ref_book'] = b_models.Book.objects.order_by('book_count')
        return context

class Delivery(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/delivery.html'


class Payment(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/payment.html'

class Contacts(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/contacts.html'

class AdminPortal(BaseTemplatePageMixin, generic.TemplateView):
    template_name='home_page/admin_portal.html'

src/orders/views.py
from django.shortcuts import render
from . import models, forms
from book import models as book_models
from django.views import generic
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
from home_page.views import BaseTemplatePageMixin
from django.contrib.auth.mixins import LoginRequiredMixin


class DelPosition(BaseTemplatePageMixin, generic.DeleteView):
    model = models.BookInCart
    success_url = reverse_lazy('orders:show-cart')
    template_name='orders/position_delete.html'

def show_cart(request):
    context = {}
    context['cart'] = None
    if request.method == 'POST':
        book_pk = request.POST.get('book_pk')
        quantity = request.POST.get('quantity')

        if book_pk and quantity:
            cart_id = request.session.get('cart_id', 0)
            if request.user.is_authenticated:
                user = request.user
            else:
                user = None
            if cart_id == 0:
                cart_id=None    
            cart, created = models.Cart.objects.get_or_create(
                pk=cart_id,
                defaults={'user':user}
                )
            context['cart'] = cart    
            if created:
                request.session['cart_id'] = cart.pk
            book = book_models.Book.objects.get(pk=book_pk)
            book_in_a_cart, created = models.BookInCart.objects.get_or_create(
                book=book,
                cart=cart,
                defaults={
                    'quantity':quantity,
                }              
            )
            if not created:
                book_in_a_cart.quantity=book_in_a_cart.quantity+int(quantity)
                book_in_a_cart.save()
    else:            
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart = models.Cart.objects.get(pk=cart_id)
            context['cart'] = cart
        

    if request.user.is_authenticated:
        context['form'] = forms.OrderForm(initial={'last_first_name' : request.user.last_name+' '+request.user.first_name,\
            'email': request.user.email,\
            'adress': request.user.profile.address1,\
            'phone_number': request.user.profile.phone_number})       
    else:
        context['form'] = forms.OrderForm()

    return render(
        request=request, 
        template_name='orders/view_cart.html', 
        context=context)

User = get_user_model()
class Order(BaseTemplatePageMixin, generic.CreateView):
    model=models.Order
    form_class=forms.OrderForm
    def form_valid(self, form):
        cart = models.Cart.objects.get(pk=self.request.session.get('cart_id'))
        form.instance.cart=cart
        return super().form_valid(form)
    def get_success_url(self):
        send_mail(
            'Заказ в магазине',
            'Заказ передан в обработку',
            'vlasova66666666@gmail.com',
            [user.email for user in User.objects.filter(groups__name='Managers')],
            fail_silently=False,
        )
        del self.request.session['cart_id']
        orderid=self.object.pk
        return reverse_lazy('orders:order-success', kwargs={'pk': orderid})

class OrderSuccess(BaseTemplatePageMixin, generic.DetailView):
    model = models.Order
    template_name='orders/success_order.html'

class OrdersAll(BaseTemplatePageMixin, LoginRequiredMixin, generic.ListView):
    model = models.Order
    template_name = 'orders/list_orders.html'

class OrdersUser(BaseTemplatePageMixin, LoginRequiredMixin, generic.ListView):
    model = models.Order
    template_name = 'orders/list_orders.html'    
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args,**kwargs)      
        return queryset.filter(cart__user__pk=self.request.user.pk)
class OrderDetail(BaseTemplatePageMixin, generic.DetailView):
    model = models.Order
    template_name = 'orders/order_detail.html'

class OrderUpdate(BaseTemplatePageMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.Order
    form_class = forms.OrderUpdateForm
    template_name = 'orders/update_orders.html'
    def get_success_url(self):
        return reverse_lazy('orders:order-detail', kwargs={'pk': self.object.pk})

class OrderCommentUpdate(BaseTemplatePageMixin, generic.UpdateView):
    model = models.Order
    form_class = forms.CommentUpdateForm
    template_name = 'orders/update_orders.html'
    def get_success_url(self):
        return reverse_lazy('orders:order-detail', kwargs={'pk': self.object.pk})

class OrderDelete(BaseTemplatePageMixin, generic.DeleteView):
    model = models.Order
    template_name='orders/order_delete.html'
    def get_success_url(self):
        return reverse_lazy('orders:orders-user')

src/orders/templates/orders/home_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
<h1>Корзина</h1>
{% endblock body %}

src/orders/templates/orders/list_orders.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список заказов
{% endblock title %}
{% block body %}
    <h1 style="text-align:center">Список заказов</h1>
    <table class="table table-bordered">
        <tr>
            <td><strong>Номер заказа</strong></td>
            <td><strong>Статус</strong></td>
            <td><strong>Фамилия Имя</strong></td>
            <td><strong>Пользователь</strong></td>
            <td><strong>Телефонный номер</strong></td>
            <td><strong>Email</strong></td>
            <td><strong>Адрес доставки</strong></td>
            <td><strong>Дата оформления заказа</strong></td>
            <td><strong>Дата изменения заказа</strong></td>
            <td><strong>Комментарий к заказу</strong></td>
            <td><strong>Отменить заказ</strong></td>
            <td><strong>Добавить комментарий</strong></td>              
        </tr>
        {% for obj in object_list %}
        <tr>
            {% for group in request.user.groups.all %}
                {% if group.name == 'Managers'%}
                    <td><a href="{% url 'orders:order-update' pk=obj.pk %}">{{obj.pk}}</a></td>
                {% else %}
                    <td>{{obj.pk}}</a></td>
                {% endif %}
            {% endfor %}            
            <td>{{obj.status}}</td>            
            <td>{{obj.last_first_name}}</td>
            <td>{{obj.cart.user.username}}</td> 
            <td>{{obj.phone_number}}</td>
            <td>{{obj.email}}</td>
            <td>{{obj.adress}}</td>           
            <td>{{obj.created_date}}</td>
            <td>{{obj.updated_date}}</td>
            <td>{{obj.information}}</td>
            <td><a href="{% url 'orders:order-delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-x-lg"></a></td>
            <td><a href="{% url 'orders:com-update' pk=obj.pk %}" class="btn btn-success"><i class="bi bi-plus-lg"></i></a></td>
        </tr>
        {% endfor %}  
    </table>
{% endblock body %}

src/orders/templates/orders/order_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
<h1>Вы уверены? Вы хотите удалить текущий заказ? </h1>
<form method='post'>
    {% csrf_token %}
    <button type="submit">Удалить</button>
</form>
{% endblock body %}

src/orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Список заказов
{% endblock title %}
{% block body %}
    <h1 style="text-align:center">Информация о заказе</h1>
    <table class="table table-bordered">
        <tr>
            <td><strong>Номер заказа</strong></td>
            <td><strong>Статус</strong></td>
            <td><strong>Фамилия Имя</strong></td>
            <td><strong>Пользователь</strong></td>
            <td><strong>Телефонный номер</strong></td>
            <td><strong>Email</strong></td>
            <td><strong>Адрес доставки</strong></td>
            <td><strong>Комментарий к заказу</strong></td>
            <td><strong>Дата оформления заказа</strong></td>
            <td><strong>Дата изменения заказа</strong></td>
        </tr>
        <tr>
            <td>{{object.pk}}</td>
            <td>{{object.status}}</td>            
            <td>{{object.last_first_name}}</td>
            <td>{{object.cart.user.username}}</td> 
            <td>{{object.phone_number}}</td>
            <td>{{object.email}}</td>
            <td>{{object.adress}}</td>
            <td>{{object.information}}</td>
            <td>{{object.created_date}}</td>
            <td>{{object.updated_date}}</td>
        </tr>
    </table>
    <!-- <a href="{% url 'orders:order-update' pk=order.pk %}">Изменить заказ</a> -->
{% endblock body %}

src/orders/templates/orders/position_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
<h1>Вы уверены? Вы хотите удалить позицию {{object.book.book_title}}? </h1>
<form method='post'>
    {% csrf_token %}
    <button type="submit">Удалить</button>
</form>
{% endblock body %}

src/orders/templates/orders/success_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
    <h1>Ваш заказ принят!</h1>
    <table class="table table-bordered">
    {%for b in object.cart.books.all%}
        <tr>
            <td>{{b.book.book_title}}</td> 
            <td>{{b.quantity}}</td>
            <td>{{b.book.book_price}}</td>
            <td>{{b.price_per_position}}</td>
        </tr>
    {% endfor %}
        <tr>
            <td><b>Итоговая стоимость товара</b></td> 
            <td></td>
            <td></td>
            <td>{{object.cart.total_price}}</td>
        </tr>
    </table>
<!-- {{object.status}} -->
{% if user.is_authenticated %}
<h5>Отменить заказ либо отследить его статус можно в профиле пользователя <a href="{% url 'orders:orders-user' %}">{{user.username}}</a></h5>
{% else %}
<h5>Изменить заказ либо отследить его статус можно по телефону +375295600616</h5>
{% endif %}
{% endblock body %}

src/orders/templates/orders/update_orders.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Создание автора
{% endblock title %}
{% block body %}
    <h1>Изменение заказа</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-secondary" value="Submit">
    </form>
{% endblock body %}

src/orders/templates/orders/view_cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Home page
{% endblock title %}
{% block body %}
<h1>Корзина</h1>
<table class="table">
    <tr>
        <td>Наименование товара</td>
        <td>Количество</td>
        <td>Цена, бел.руб.</td>
        <td>Стоимость за все позиции, бел.руб.</td>
        <td>Удаление позиций</td>
    </tr>
{% for book_in_cart in cart.books.all %}
    <tr>
        <td>{{book_in_cart.book.book_title}}</td>
        <td>{{book_in_cart.quantity}}</td>
        <td>{{book_in_cart.book.book_price}}</td>
        <td>{{book_in_cart.price_per_position}}</td>
        <td><a href="{% url 'orders:del-position' book_in_cart.pk %}" class="btn"><i class="bi bi-x-circle"></i></a></td>
    </tr>
{% endfor %}
    <tr>
        <td colspan="2"></td>
        <td>Итоговая стоимость</td>
        <td colspan="2">{{cart.total_price}}</td>
    </tr>
</table>
{% if not cart.books.all %}
<h4>Ваша корзина пуста</h4>
{% else %}
<form action="{% url 'orders:create-order' %}" method="post" >
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success">Сделать заказ</button>
</form>
{% endif %}
{% endblock body %}